/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2pbo;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lenovo Flex 6-14
 */
public class tp2pbo extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    ArrayList<Mobil> listMobil;
    String header[] = new String[]{"No", "Merk", "Plat", "Warna", "Jenis"};
    DefaultTableModel dtm;
    int row,col;
    /**
     * Creates new form tp2pbo
     */
    public tp2pbo() {
        initComponents();
        
        listMobil = new ArrayList<>();
        dtm = new DefaultTableModel(header, 0);
        mobil_table.setModel(dtm);
        
        form_panel.setVisible(false);
        table_panel.setVisible(false);
        info_panel.setVisible(false);
        jenis_label.setVisible(true);
        jenis_cb.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JLabel();
        nav_panel = new javax.swing.JPanel();
        form_button = new javax.swing.JButton();
        table_button = new javax.swing.JButton();
        info_button = new javax.swing.JButton();
        title_label = new javax.swing.JLabel();
        form_panel = new javax.swing.JPanel();
        merk_label = new javax.swing.JLabel();
        plat_label = new javax.swing.JLabel();
        warna_label = new javax.swing.JLabel();
        jenis_label = new javax.swing.JLabel();
        merk_tf = new javax.swing.JTextField();
        plat_tf = new javax.swing.JTextField();
        warna_tf = new javax.swing.JTextField();
        jenis_cb = new javax.swing.JComboBox<>();
        submit_button = new javax.swing.JButton();
        table_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mobil_table = new javax.swing.JTable();
        info_panel = new javax.swing.JPanel();
        nama_label = new javax.swing.JLabel();
        nim_label = new javax.swing.JLabel();
        foto_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcome.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(0, 51, 51));
        welcome.setText("Selamat Datang!");

        nav_panel.setBackground(new java.awt.Color(102, 255, 102));

        form_button.setBackground(new java.awt.Color(255, 255, 255));
        form_button.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        form_button.setForeground(new java.awt.Color(0, 0, 0));
        form_button.setText("Form");
        form_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form_buttonMouseClicked(evt);
            }
        });

        table_button.setBackground(new java.awt.Color(255, 255, 255));
        table_button.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        table_button.setForeground(new java.awt.Color(0, 0, 0));
        table_button.setText("Table");
        table_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_buttonMouseClicked(evt);
            }
        });
        table_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_buttonActionPerformed(evt);
            }
        });

        info_button.setBackground(new java.awt.Color(255, 255, 255));
        info_button.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        info_button.setForeground(new java.awt.Color(0, 0, 0));
        info_button.setText("Info");
        info_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                info_buttonMouseClicked(evt);
            }
        });

        title_label.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        title_label.setForeground(new java.awt.Color(0, 0, 0));
        title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_label.setText("Data Mobil");

        javax.swing.GroupLayout nav_panelLayout = new javax.swing.GroupLayout(nav_panel);
        nav_panel.setLayout(nav_panelLayout);
        nav_panelLayout.setHorizontalGroup(
            nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(form_button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table_button, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info_button, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title_label)
                .addGap(114, 114, 114))
        );
        nav_panelLayout.setVerticalGroup(
            nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(title_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(form_button, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(table_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        form_panel.setBackground(new java.awt.Color(255, 255, 255));

        merk_label.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        merk_label.setForeground(new java.awt.Color(0, 0, 0));
        merk_label.setText("Merk");

        plat_label.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        plat_label.setForeground(new java.awt.Color(0, 0, 0));
        plat_label.setText("Plat");

        warna_label.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        warna_label.setForeground(new java.awt.Color(0, 0, 0));
        warna_label.setText("Warna");

        jenis_label.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jenis_label.setForeground(new java.awt.Color(0, 0, 0));
        jenis_label.setText("Jenis");

        merk_tf.setBackground(new java.awt.Color(255, 255, 255));
        merk_tf.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        plat_tf.setBackground(new java.awt.Color(255, 255, 255));
        plat_tf.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        warna_tf.setBackground(new java.awt.Color(255, 255, 255));
        warna_tf.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jenis_cb.setBackground(new java.awt.Color(255, 255, 255));
        jenis_cb.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jenis_cb.setForeground(new java.awt.Color(0, 0, 0));
        jenis_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biasa", "Balap", "Sport", "Truk" }));

        submit_button.setBackground(new java.awt.Color(255, 255, 255));
        submit_button.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        submit_button.setForeground(new java.awt.Color(0, 0, 0));
        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout form_panelLayout = new javax.swing.GroupLayout(form_panel);
        form_panel.setLayout(form_panelLayout);
        form_panelLayout.setHorizontalGroup(
            form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_panelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(merk_label)
                    .addComponent(plat_label)
                    .addComponent(warna_label)
                    .addComponent(jenis_label))
                .addGap(18, 18, 18)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(plat_tf)
                        .addComponent(merk_tf)
                        .addComponent(warna_tf)
                        .addComponent(jenis_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        form_panelLayout.setVerticalGroup(
            form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_panelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(merk_label)
                    .addComponent(merk_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plat_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plat_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warna_label)
                    .addComponent(warna_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(form_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jenis_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jenis_cb))
                .addGap(46, 46, 46)
                .addComponent(submit_button)
                .addGap(66, 66, 66))
        );

        table_panel.setBackground(new java.awt.Color(255, 255, 255));
        table_panel.setForeground(new java.awt.Color(51, 51, 51));

        mobil_table.setBackground(new java.awt.Color(255, 255, 255));
        mobil_table.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mobil_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Merk", "Plat", "Warna", "Jenis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mobil_table);

        javax.swing.GroupLayout table_panelLayout = new javax.swing.GroupLayout(table_panel);
        table_panel.setLayout(table_panelLayout);
        table_panelLayout.setHorizontalGroup(
            table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
            .addGroup(table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(table_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        table_panelLayout.setVerticalGroup(
            table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(table_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        info_panel.setBackground(new java.awt.Color(255, 255, 255));
        info_panel.setForeground(new java.awt.Color(0, 0, 0));

        nama_label.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nama_label.setForeground(new java.awt.Color(0, 102, 0));
        nama_label.setText("Nama : Sarah Hanifah");

        nim_label.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nim_label.setForeground(new java.awt.Color(0, 102, 0));
        nim_label.setText("NIM : 1909331");

        foto_label.setForeground(new java.awt.Color(0, 102, 0));
        foto_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp2pbo/image/sarah.JPG"))); // NOI18N
        foto_label.setText("jLabel1");

        javax.swing.GroupLayout info_panelLayout = new javax.swing.GroupLayout(info_panel);
        info_panel.setLayout(info_panelLayout);
        info_panelLayout.setHorizontalGroup(
            info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
            .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_panelLayout.createSequentialGroup()
                    .addContainerGap(33, Short.MAX_VALUE)
                    .addComponent(nama_label, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(78, Short.MAX_VALUE)))
            .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_panelLayout.createSequentialGroup()
                    .addContainerGap(33, Short.MAX_VALUE)
                    .addComponent(nim_label, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(170, Short.MAX_VALUE)))
            .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_panelLayout.createSequentialGroup()
                    .addContainerGap(117, Short.MAX_VALUE)
                    .addComponent(foto_label, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );
        info_panelLayout.setVerticalGroup(
            info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_panelLayout.createSequentialGroup()
                    .addContainerGap(283, Short.MAX_VALUE)
                    .addComponent(nama_label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(136, Short.MAX_VALUE)))
            .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_panelLayout.createSequentialGroup()
                    .addContainerGap(323, Short.MAX_VALUE)
                    .addComponent(nim_label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
            .addGroup(info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_panelLayout.createSequentialGroup()
                    .addContainerGap(59, Short.MAX_VALUE)
                    .addComponent(foto_label, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(217, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nav_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(form_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(info_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(table_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nav_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(form_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 181, Short.MAX_VALUE)
                    .addComponent(info_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 175, Short.MAX_VALUE)
                    .addComponent(table_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(283, 283, 283)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(253, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void form_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form_buttonMouseClicked
        // TODO add your handling code here:
        form_panel.setVisible(true);
        table_panel.setVisible(false);
        info_panel.setVisible(false);
    }//GEN-LAST:event_form_buttonMouseClicked

    private void table_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_buttonMouseClicked
        // TODO add your handling code here:
        form_panel.setVisible(false);
        table_panel.setVisible(true);
        info_panel.setVisible(false);
    }//GEN-LAST:event_table_buttonMouseClicked

    private void info_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info_buttonMouseClicked
        // TODO add your handling code here:
        form_panel.setVisible(false);
        table_panel.setVisible(false);
        info_panel.setVisible(true);
    }//GEN-LAST:event_info_buttonMouseClicked

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
        //Menambahkan data ke Database
        try
        {
            String sql = "insert into mobil (merk, plat, warna, jenis) values (?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/db_tp2pbo2021","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1, merk_tf.getText());
            pst.setString(2, plat_tf.getText());
            pst.setString(3, warna_tf.getText());
            pst.setString(4, (String) jenis_cb.getSelectedItem());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan! :D");

        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        merk_tf.setText("");
        plat_tf.setText("");
        warna_tf.setText("");
        jenis_cb.setSelectedIndex(0);
        table_button.setVisible(true);
        info_button.setVisible(true);
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void table_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_buttonActionPerformed
        // TODO add your handling code here:
        //Menampilkan data di tabel sesuai Database
        try
        {
            String sql = "select * from mobil";
            con = DriverManager.getConnection("jdbc:mysql://localhost/db_tp2pbo2021","root","");
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            mobil_table.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_table_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tp2pbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tp2pbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tp2pbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tp2pbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tp2pbo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton form_button;
    private javax.swing.JPanel form_panel;
    private javax.swing.JLabel foto_label;
    private javax.swing.JButton info_button;
    private javax.swing.JPanel info_panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis_cb;
    private javax.swing.JLabel jenis_label;
    private javax.swing.JLabel merk_label;
    private javax.swing.JTextField merk_tf;
    private javax.swing.JTable mobil_table;
    private javax.swing.JLabel nama_label;
    private javax.swing.JPanel nav_panel;
    private javax.swing.JLabel nim_label;
    private javax.swing.JLabel plat_label;
    private javax.swing.JTextField plat_tf;
    private javax.swing.JButton submit_button;
    private javax.swing.JButton table_button;
    private javax.swing.JPanel table_panel;
    private javax.swing.JLabel title_label;
    private javax.swing.JLabel warna_label;
    private javax.swing.JTextField warna_tf;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
